USE master
CREATE DATABASE BD_ELGUSTAZO

USE BD_ELGUSTAZO
CREATE TABLE PRODUCTOS
(    
    ID_producto INT PRIMARY KEY IDENTITY NOT NULL,
	nomb VARCHAR (26)NOT NULL,
	preciovent FLOAT NOT NULL,
	preciocom FLOAT NOT NULL,
	canti FLOAT NOT NULL,
	fechavenci DATE NOT NULL,
	descrip VARCHAR (100),
 )

 USE BD_ELGUSTAZO
 CREATE TABLE EMPLEADOS
 (
    ID_empleado INT PRIMARY KEY IDENTITY NOT NULL,
	nomb1 VARCHAR (26)NOT NULL,
	nomb2 VARCHAR (26)NOT NULL,
	apell1 VARCHAR (26)NOT NULL,
	apell2 VARCHAR (26)NOT NULL,
    numcelu VARCHAR (8)NOT NULL,
	direc VARCHAR (30)NOT NULL,
  )


  USE BD_ELGUSTAZO
  CREATE TABLE CLIENTES 
 ( 
 
    cedula VARCHAR (14) PRIMARY KEY NOT NULL,
	nomb1 VARCHAR (26)NOT NULL,
	nomb2 VARCHAR (26)NOT NULL,
	apell1 VARCHAR (26)NOT NULL,
	apell2 VARCHAR (26)NOT NULL,
	numcelu VARCHAR (8) NOT NULL,
	direc VARCHAR (30) NOT NULL,
 )


 USE BD_ELGUSTAZO
  CREATE TABLE VENTAS
 ( 
    ID_venta INT PRIMARY KEY IDENTITY NOT NULL,
	fecha DATE NOT NULL,
 )

 USE BD_ELGUSTAZO
  CREATE TABLE TURNOS
 ( 
    ID_turnos INT PRIMARY KEY IDENTITY NOT NULL,
	nomb VARCHAR (26) NOT NULL,
	hrainicio TIME NOT NULL,
	hrafinali TIME NOT NULL,
 )


  USE BD_ELGUSTAZO
  CREATE TABLE TIPOCATEGORIA
 ( 
    ID_categoria INT PRIMARY KEY IDENTITY NOT NULL,
	nomb VARCHAR (26)NOT NULL,
 )


   USE BD_ELGUSTAZO
  CREATE TABLE DEVOLUCIONES
 ( 
    ID_devolu INT PRIMARY KEY IDENTITY NOT NULL,
	descrip VARCHAR (100),
	canti FLOAT NOT NULL,
	fecha DATE NOT NULL, 
    

  )


    USE BD_ELGUSTAZO
  CREATE TABLE COMPRAS
 ( 
    ID_compra INT PRIMARY KEY IDENTITY NOT NULL,
	fecha DATE NOT NULL,
   

  )

    USE BD_ELGUSTAZO
  CREATE TABLE PROVEEDORES
 ( 
    ruc VARCHAR (16) PRIMARY KEY NOT NULL,
	nomb VARCHAR (26) NOT NULL,
	numcelu VARCHAR (8)NOT NULL,
	direc VARCHAR (30)NOT NULL,
  )


  ALTER TABLE dbo.VENTAS
ADD cedula VARCHAR (14) NOT NULL

ALTER TABLE dbo.VENTAS
ADD CONSTRAINT FK_CLIENTES_VENTAS
FOREIGN KEY (cedula)
REFERENCES dbo.CLIENTES(cedula)


ALTER TABLE dbo.VENTAS
ADD ID_empleado INT NOT NULL


ALTER TABLE dbo.VENTAS
ADD CONSTRAINT FK_EMPLEADO_VENTAS
FOREIGN KEY (ID_empleado)
REFERENCES dbo.EMPLEADOS(ID_empleado)


ALTER TABLE dbo.EMPLEADOS
ADD ID_turnos INT NOT NULL


ALTER TABLE dbo.EMPLEADOS
ADD CONSTRAINT FK_EMPLEADO_TURNO
FOREIGN KEY (ID_turnos)
REFERENCES dbo.TURNOS(ID_turnos)


ALTER TABLE dbo.PRODUCTOS
ADD ID_categoria INT NOT NULL


ALTER TABLE dbo.PRODUCTOS
ADD CONSTRAINT FK_PRODUCTO_TIPOCATEGORIA
FOREIGN KEY (ID_categoria)
REFERENCES dbo.TIPOCATEGORIA(ID_categoria)

ALTER TABLE dbo.DEVOLUCIONES
ADD ID_producto INT NOT NULL


ALTER TABLE dbo.DEVOLUCIONES
ADD CONSTRAINT FK_DEVOLUCION_PRODUCTO
FOREIGN KEY (ID_producto)
REFERENCES dbo.PRODUCTOS(ID_producto)



ALTER TABLE dbo.COMPRAS
ADD ruc VARCHAR (16) NOT NULL


ALTER TABLE dbo.COMPRAS
ADD CONSTRAINT FK_COMPRAS_PRODUCTO
FOREIGN KEY (ruc)
REFERENCES dbo.PROVEEDORES(ruc)


USE BD_ELGUSTAZO
 CREATE TABLE VENTA_PRODUCTO
 (
    nrofactura INT PRIMARY KEY IDENTITY,
    fecha DATE,
	canti FLOAT ,
	monto FLOAT ,
	tipo_venta bit ,
	direc VARCHAR (30),

  )

  ALTER TABLE dbo.VENTA_PRODUCTO
ADD ID_producto INT  NOT NULL


ALTER TABLE dbo.VENTA_PRODUCTO
ADD CONSTRAINT FK_TRANSACCION 
FOREIGN KEY (ID_producto)
REFERENCES dbo.PRODUCTOS(ID_producto)

  ALTER TABLE dbo.VENTA_PRODUCTO
ADD ID_venta INT  NOT NULL


ALTER TABLE dbo.VENTA_PRODUCTO
ADD CONSTRAINT FK_TRANSACCION1
FOREIGN KEY ( ID_venta)
REFERENCES dbo.VENTAS( ID_venta)


USE BD_ELGUSTAZO
 CREATE TABLE COMPRA_PRODUCTO
 (
    ID_nrofactura1 INT PRIMARY KEY IDENTITY,
    fecha DATE,
	canti FLOAT ,
	monto FLOAT ,

  )


  ALTER TABLE dbo.COMPRA_PRODUCTO
ADD ID_producto INT  NOT NULL


ALTER TABLE dbo.COMPRA_PRODUCTO
ADD CONSTRAINT FK_COMPRAS
FOREIGN KEY ( ID_producto)
REFERENCES dbo.PRODUCTOS( ID_producto)

ALTER TABLE dbo.COMPRA_PRODUCTO
ADD ID_compra INT  NOT NULL


ALTER TABLE dbo.COMPRA_PRODUCTO
ADD CONSTRAINT FK_COMPRAS1
FOREIGN KEY ( ID_compra)
REFERENCES dbo.COMPRAS( ID_compra)












