/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Cris
 */
public class Registroempleado extends javax.swing.JInternalFrame {

    /**
     * Creates new form Registroempleado
     */
    public Registroempleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SegunNombre1 = new javax.swing.JLabel();
        lavelapellido1 = new javax.swing.JLabel();
        PrimNombre1 = new javax.swing.JLabel();
        lavelapellido = new javax.swing.JLabel();
        SegunNombre2 = new javax.swing.JLabel();
        PrimNombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextRuc = new javax.swing.JTextField();
        jTextRuc1 = new javax.swing.JTextField();
        jTextRuc2 = new javax.swing.JTextField();
        jTextRuc3 = new javax.swing.JTextField();
        jTextRuc4 = new javax.swing.JTextField();
        jTextRuc5 = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SegunNombre1.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        SegunNombre1.setForeground(new java.awt.Color(255, 255, 255));
        SegunNombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SegunNombre1.setText("Dirección:");
        jPanel1.add(SegunNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        lavelapellido1.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lavelapellido1.setForeground(new java.awt.Color(255, 255, 255));
        lavelapellido1.setText("PRIMER APELLIDO :");
        jPanel1.add(lavelapellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        PrimNombre1.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        PrimNombre1.setForeground(new java.awt.Color(255, 255, 255));
        PrimNombre1.setText("PRIMER NOMBRE :");
        jPanel1.add(PrimNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        lavelapellido.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lavelapellido.setForeground(new java.awt.Color(255, 255, 255));
        lavelapellido.setText("SEGUNDO APELLIDO:");
        jPanel1.add(lavelapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, -1));

        SegunNombre2.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        SegunNombre2.setForeground(new java.awt.Color(255, 255, 255));
        SegunNombre2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SegunNombre2.setText("N-Telefóno:");
        jPanel1.add(SegunNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, -1, -1));

        PrimNombre.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        PrimNombre.setForeground(new java.awt.Color(255, 255, 255));
        PrimNombre.setText("SEGUNDO NOMBRE :");
        jPanel1.add(PrimNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registro Empleado");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jTextRuc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        jPanel1.add(jTextRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 210, -1));

        jTextRuc1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        jPanel1.add(jTextRuc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 210, -1));

        jTextRuc2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        jPanel1.add(jTextRuc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 210, -1));

        jTextRuc3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        jPanel1.add(jTextRuc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 210, -1));

        jTextRuc4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        jPanel1.add(jTextRuc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 210, -1));

        jTextRuc5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        jPanel1.add(jTextRuc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 210, -1));

        jButtonGuardar.setBackground(new java.awt.Color(0, 51, 102));
        jButtonGuardar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButtonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 110, 40));

        jButtonCancelar.setBackground(new java.awt.Color(0, 51, 102));
        jButtonCancelar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");
        jPanel1.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/textura-madera-en-negro_2560x1600_xtrafondos.com.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PrimNombre;
    private javax.swing.JLabel PrimNombre1;
    private javax.swing.JLabel SegunNombre1;
    private javax.swing.JLabel SegunNombre2;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextRuc;
    private javax.swing.JTextField jTextRuc1;
    private javax.swing.JTextField jTextRuc2;
    private javax.swing.JTextField jTextRuc3;
    private javax.swing.JTextField jTextRuc4;
    private javax.swing.JTextField jTextRuc5;
    private javax.swing.JLabel lavelapellido;
    private javax.swing.JLabel lavelapellido1;
    // End of variables declaration//GEN-END:variables
}
